import type { Language } from "../domain/mission-contracts";

export const REQUIRED_UI_KEYS = [
  "language_label", "portuguese", "english", "start", "start_hint",
  "tagline", "before_start", "name_question", "name_help", "name_label",
  "name_placeholder", "name_error", "enter_city", "back", "loading_city",
  "loading_error", "missions_complete", "city_status", "recommended_next",
  "choose_mission", "choose_mission_help", "choose_mission_label",
  "mission_concept", "mission_objective", "expected_outcome", "mission_purpose",
  "briefing", "hint", "your_plan", "prompt_placeholder",
  "submit_plan", "evaluating", "feedback", "next_mission", "journey_complete",
  "retry", "start_voice", "stop_voice", "voice_optional",
  "voice_ready", "voice_connecting", "voice_listening", "voice_speaking",
  "voice_permission_denied", "voice_error", "voice_unavailable",
  "voice_unavailable_action", "return_to_text",
  "camera_overview", "camera_mission", "explore_help", "npc_issue",
  "npc_empty", "day", "budget", "city_health", "error_invalid_request",
  "checkpoint_complete", "checkpoint_new", "checkpoint_pending", "checkpoint_regressed",
  "error_rate_limited", "error_provider_unavailable", "error_invalid_response",
  "error_network", "error_timeout", "error_unknown", "audio", "audio_off",
  "music", "ambience", "mute", "unmute", "entry_audio_label", "entry_mute",
  "entry_unmute", "volume_down", "volume_up", "volume_level", "prototype",
  "city_canvas_label", "mission_navigation_label", "camera_controls_label",
] as const;

export type UiCopyKey = (typeof REQUIRED_UI_KEYS)[number];
type UiCopy = Record<UiCopyKey, string>;

export const UI_COPY: Record<Language, UiCopy> = {
  portuguese: {
    language_label: "Idioma", portuguese: "Português", english: "English",
    start: "Começar", start_hint: "clique ou pressione Espaço",
    tagline: "Uma cidade feita de escolhas, educação e inteligência artificial.",
    before_start: "Antes de começar", name_question: "Como podemos chamar você?",
    name_help: "A cidade espera sua primeira decisão como prefeito.", name_label: "Seu nome",
    name_placeholder: "Digite seu nome", name_error: "Digite pelo menos duas letras.",
    enter_city: "Entrar em AI City", back: "Voltar", loading_city: "Construindo a cidade…",
    loading_error: "Não foi possível carregar a cidade. Recarregue para tentar novamente.",
    missions_complete: "Missões concluídas", city_status: "Estado da cidade",
    recommended_next: "Próxima missão recomendada", mission_concept: "Conceito",
    choose_mission: "Escolha uma missão", choose_mission_label: "Quatro caminhos disponíveis",
    choose_mission_help: "Comece por moradia, saúde, diagnóstico urbano ou escola. A recomendação é apenas uma sugestão; você pode trocar quando quiser.",
    mission_objective: "Objetivo", expected_outcome: "Resultado esperado",
    mission_purpose: "Por que escolher esta missão",
    briefing: "Briefing", hint: "Dica", your_plan: "Seu plano para a cidade",
    prompt_placeholder: "Descreva objetivo, pessoas atendidas, requisitos, limites e como medir sucesso…",
    submit_plan: "Avaliar plano", evaluating: "Avaliando com segurança…", feedback: "Feedback",
    next_mission: "Escolher outra missão", journey_complete: "Jornada concluída",
    retry: "Tentar novamente",
    checkpoint_complete: "Concluído", checkpoint_new: "Corrigido agora",
    checkpoint_pending: "Ainda falta", checkpoint_regressed: "Revisado",
    start_voice: "Iniciar conversa por voz", stop_voice: "Encerrar voz",
    voice_optional: "Opcional · usa conexão Realtime somente após sua confirmação",
    voice_ready: "Voz pronta — o microfone só abre quando você escolher.",
    voice_connecting: "Conectando com segurança…", voice_listening: "Ouvindo — fale seu plano.",
    voice_speaking: "Conversa ativa — o mentor está respondendo.",
    voice_permission_denied: "Microfone bloqueado. Libere a permissão ou continue por texto.",
    voice_error: "A voz foi interrompida. Seu texto e progresso continuam seguros.",
    voice_unavailable: "Voz indisponível neste navegador. Continue por texto.",
    voice_unavailable_action: "Voz indisponível", return_to_text: "Voltar ao texto",
    camera_overview: "Visão geral", camera_mission: "Focar missão",
    explore_help: "Explore com WASD ou setas. Toque ou clique no chão para ir até lá.",
    npc_issue: "Relato dos moradores", npc_empty: "Aproxime-se de um morador para ouvir o relato.",
    day: "Dia", budget: "Orçamento", city_health: "Bem-estar",
    error_invalid_request: "Revise o plano e tente novamente.",
    error_rate_limited: "Muitas avaliações agora. Aguarde um minuto e tente novamente.",
    error_provider_unavailable: "A avaliação está indisponível. Seu progresso foi preservado; tente novamente.",
    error_invalid_response: "Recebemos uma resposta inválida. Tente novamente sem perder o progresso.",
    error_network: "Sem conexão com o servidor. Verifique sua rede e tente novamente.",
    error_timeout: "A avaliação excedeu o tempo limite. Tente novamente.",
    error_unknown: "Algo deu errado. Seu progresso está seguro; tente novamente.",
    audio: "Som", audio_off: "Som desligado", music: "Trilha sonora",
    ambience: "Sons da cidade", mute: "Silenciar", unmute: "Ativar",
    entry_audio_label: "Controles de som", entry_mute: "Silenciar som",
    entry_unmute: "Ativar som", volume_down: "Diminuir volume",
    volume_up: "Aumentar volume", volume_level: "Nível do som: {level}",
    prototype: "Protótipo do hackathon da OpenAI",
    city_canvas_label: "Cidade 3D interativa de AI City",
    mission_navigation_label: "Missões de aprendizagem",
    camera_controls_label: "Controles da câmera",
  },
  english: {
    language_label: "Language", portuguese: "Português", english: "English",
    start: "Start", start_hint: "click or press Space",
    tagline: "A city shaped by choices, education, and artificial intelligence.",
    before_start: "Before you begin", name_question: "What should we call you?",
    name_help: "The city awaits your first decision as mayor.", name_label: "Your name",
    name_placeholder: "Enter your name", name_error: "Enter at least two letters.",
    enter_city: "Enter AI City", back: "Back", loading_city: "Building the city…",
    loading_error: "The city could not load. Reload to try again.",
    missions_complete: "Missions complete", city_status: "City status",
    recommended_next: "Recommended next mission", mission_concept: "Concept",
    choose_mission: "Choose a mission", choose_mission_label: "Four paths available",
    choose_mission_help: "Start with housing, health, urban diagnosis, or a school. The recommendation is only a suggestion; switch whenever you want.",
    mission_objective: "Objective", expected_outcome: "Expected outcome",
    mission_purpose: "Why choose this mission",
    briefing: "Briefing", hint: "Hint", your_plan: "Your city plan",
    prompt_placeholder: "Describe the goal, people served, requirements, constraints, and how success will be measured…",
    submit_plan: "Evaluate plan", evaluating: "Evaluating safely…", feedback: "Feedback",
    next_mission: "Choose another mission", journey_complete: "Journey complete",
    retry: "Try again",
    checkpoint_complete: "Complete", checkpoint_new: "Fixed now",
    checkpoint_pending: "Still needed", checkpoint_regressed: "Revised",
    start_voice: "Start voice conversation", stop_voice: "End voice",
    voice_optional: "Optional · uses Realtime only after you confirm",
    voice_ready: "Voice ready — microphone opens only when you choose.",
    voice_connecting: "Connecting securely…", voice_listening: "Listening — describe your plan.",
    voice_speaking: "Conversation active — the mentor is responding.",
    voice_permission_denied: "Microphone permission denied. Allow it or continue with text.",
    voice_error: "Voice stopped. Your text and progress remain safe.",
    voice_unavailable: "Voice is unavailable in this browser. Continue with text.",
    voice_unavailable_action: "Voice unavailable", return_to_text: "Return to text",
    camera_overview: "Overview", camera_mission: "Focus mission",
    explore_help: "Explore with WASD or arrow keys. Tap or click the ground to move there.",
    npc_issue: "Resident report", npc_empty: "Approach a resident to hear their report.",
    day: "Day", budget: "Budget", city_health: "Well-being",
    error_invalid_request: "Review your plan and try again.",
    error_rate_limited: "Too many evaluations right now. Wait a minute and try again.",
    error_provider_unavailable: "Evaluation is unavailable. Your progress is preserved; try again.",
    error_invalid_response: "We received an invalid response. Try again without losing progress.",
    error_network: "Cannot reach the server. Check your connection and try again.",
    error_timeout: "Evaluation timed out. Try again.",
    error_unknown: "Something went wrong. Your progress is safe; try again.",
    audio: "Sound", audio_off: "Sound off", music: "Music",
    ambience: "City sounds", mute: "Mute", unmute: "Turn on",
    entry_audio_label: "Sound controls", entry_mute: "Mute sound",
    entry_unmute: "Turn on sound", volume_down: "Lower volume",
    volume_up: "Raise volume", volume_level: "Volume: {level}",
    prototype: "OpenAI hackathon prototype",
    city_canvas_label: "AI City interactive 3D city",
    mission_navigation_label: "Learning missions",
    camera_controls_label: "Camera controls",
  },
};

function humanize(key: string): string {
  const words = key.replace(/[_-]+/g, " ").trim();
  return words ? words[0]!.toUpperCase() + words.slice(1) : "Missing text";
}

export function uiText(language: Language, key: string): string {
  return (UI_COPY[language] as Record<string, string>)[key]
    ?? (UI_COPY.portuguese as Record<string, string>)[key]
    ?? humanize(key);
}
